/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appKasirLaundry;

/**
 *
 * @author HP
 */
import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class appKasirISL extends javax.swing.JFrame {

    private static int idCounter = 1; // Counter untuk ID pelanggan otomatis

    /**
     * Creates new form appKasirISL
     */
    public appKasirISL() {
        initComponents();
        generateIdPelanggan(); // Inisialisasi ID
        setNoTelepon(); // Membatasi input noTelepon hanya untuk angka
        comboBoxData(); // Inisialisasi data ComboBox
        setupBeratSpinner(); // Konfigurasi spinner "Berat"
    }

    private void generateIdPelanggan() {
        id_pelanggan.setText("KL-ISL" + String.format("%04d", idCounter++)); // Format ID jadi PLG0001, PLG0002, dst.   
        id_pelanggan.setEditable(false); // ID pelanggan tidak bisa diubah
    }

    private void setNoTelepon() {
        // Pendekatan menggunakan KeyListener
        noTelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume(); // Batalkan input jika bukan angka
                }
            }
        });
    }

    private void comboBoxData() {
        jenisLayanan.addItem("Cuci Kering");
        jenisLayanan.addItem("Cuci Setrika");
        jenisLayanan.addItem("Setrika Saja");
        jenisLayanan.addItem("Dry Cleaning");

        jenisBarang.addItem("Pakaian");
        jenisBarang.addItem("Sprei");
        jenisBarang.addItem("Selimut");
        jenisBarang.addItem("Jas");

        jenisParfum.addItem("Lavender");
        jenisParfum.addItem("Mawar");
        jenisParfum.addItem("Jeruk");
        jenisParfum.addItem("Tanpa Parfum");
    }

    private void setupBeratSpinner() {
        // Model spinner dengan nilai awal = 1, minimum = 1, maksimum = 50, step = 1
        SpinnerNumberModel beratModel = new SpinnerNumberModel(1, 1, 50, 1);
        Berat.setModel(beratModel);

        // Listener untuk memastikan nilai tidak kurang dari 1
        Berat.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                int value = (int) Berat.getValue();
                if (value < 1) {
                    Berat.setValue(1); // Tetapkan nilai minimum ke 1
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        Berat = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        noTelepon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jenisLayanan = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jenisBarang = new javax.swing.JComboBox<>();
        totalPembayaran = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaPelanggan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        id_pelanggan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jenisParfum = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataKasir = new javax.swing.JTable();
        hapusData = new javax.swing.JButton();
        hapusDataAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel14.setText("(kg)");

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        Berat.setVerifyInputWhenFocusTarget(false);
        Berat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BeratStateChanged(evt);
            }
        });

        jLabel7.setText("No Telepon           :");

        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });

        jLabel8.setText("Alamat                   :");

        noTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTeleponActionPerformed(evt);
            }
        });

        jLabel9.setText("Jenis Layanan        :");

        jLabel10.setText("Jenis Barang          :");

        jenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisBarangActionPerformed(evt);
            }
        });

        totalPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPembayaranActionPerformed(evt);
            }
        });

        jLabel11.setText("Berat                         :");

        jLabel12.setText("Harga  (kg             :");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("KASIR LAUNDRY");

        jLabel2.setText("(NAMA LANDRY)");

        jLabel3.setText("Jl. Bendungan Siguragura No. 31D ");

        jLabel4.setText("HP : 085697953213");

        jLabel5.setText("ID Pelanggan :");

        namaPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPelangganActionPerformed(evt);
            }
        });

        jLabel6.setText("Nama Pelanggan :");

        id_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pelangganActionPerformed(evt);
            }
        });

        jLabel15.setText("Total Pembayaran         :");

        jLabel13.setText("Jenis Parfum           :");

        tabelDataKasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Pelanggan", "Nama Pengguna", "No Telepon", "Alamat", "Jenis Layanan", "Jenis Barang", "Berat", "Harga", "Jenis Parfum", "Total Bayar"
            }
        ));
        tabelDataKasir.setShowHorizontalLines(true);
        tabelDataKasir.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tabelDataKasir);

        hapusData.setText("Hapus Data");
        hapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusDataActionPerformed(evt);
            }
        });

        hapusDataAll.setText("Bersihkan JFrame");
        hapusDataAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusDataAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(7, 7, 7)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel5)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(2, 2, 2)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel12)
                                                            .addComponent(jLabel13))
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(id_pelanggan, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(namaPelanggan, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(noTelepon, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(alamat, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jenisLayanan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jenisBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(totalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Berat)
                                                    .addComponent(jenisParfum, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(189, 189, 189)
                                        .addComponent(hitung)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(jLabel2))
                                                .addComponent(jLabel1)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(36, 36, 36)
                                            .addComponent(jLabel4))
                                        .addComponent(jLabel3))
                                    .addGap(150, 150, 150)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hapusData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hapusDataAll)))
                        .addGap(0, 372, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(id_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(namaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(noTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(Berat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisParfum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hitung)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(totalPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapusData)
                    .addComponent(hapusDataAll))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        // Mendapatkan pilihan dari combo box
        String layanan = (String) jenisLayanan.getSelectedItem();
        String barang = (String) jenisBarang.getSelectedItem();
        String parfum = (String) jenisParfum.getSelectedItem();
        int berat = (int) Berat.getValue();

        // Menentukan harga per item
        int hargaLayanan = 0, hargaBarang = 0, hargaParfum = 0;

        // Harga berdasarkan layanan
        switch (layanan) {
            case "Cuci Kering":
                hargaLayanan = 2000;
                break;
            case "Cuci Setrika":
                hargaLayanan = 3000;
                break;
            case "Setrika Saja":
                hargaLayanan = 1000;
                break;
            case "Dry Cleaning":
                hargaLayanan = 5000;
                break;
        }

        // Harga berdasarkan barang
        switch (barang) {
            case "Pakaian":
                hargaBarang = 4000;
                break;
            case "Sprei":
                hargaBarang = 6000;
                break;
            case "Selimut":
                hargaBarang = 8000;
                break;
            case "Jas":
                hargaBarang = 7000;
                break;
        }

        // Harga berdasarkan parfum
        switch (parfum) {
            case "Lavender":
                hargaParfum = 2000;
                break;
            case "Mawar":
                hargaParfum = 1500;
                break;
            case "Jeruk":
                hargaParfum = 1000;
                break;
            case "Tanpa Parfum":
                hargaParfum = 0;
                break;
        }

        // Menghitung total harga per kilogram
        int hargaPerKg = hargaLayanan + hargaBarang;
        harga.setText(String.valueOf(hargaPerKg)); // Menampilkan harga per kilogram di input Harga(kg)

        // Menghitung total pembayaran
        int totalBayar = (hargaPerKg * berat) + hargaParfum;
        totalPembayaran.setText(String.valueOf(totalBayar)); // Menampilkan total pembayaran
        
        
    }//GEN-LAST:event_hitungActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void noTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTeleponActionPerformed

    private void jenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisBarangActionPerformed

    private void totalPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPembayaranActionPerformed

    private void namaPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPelangganActionPerformed

    private void id_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_pelangganActionPerformed

    private void hapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusDataActionPerformed

    private void hapusDataAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusDataAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusDataAllActionPerformed

    private void BeratStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BeratStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BeratStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appKasirISL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appKasirISL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appKasirISL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appKasirISL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appKasirISL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Berat;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton hapusData;
    private javax.swing.JButton hapusDataAll;
    private javax.swing.JTextField harga;
    private javax.swing.JButton hitung;
    private javax.swing.JTextField id_pelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenisBarang;
    private javax.swing.JComboBox<String> jenisLayanan;
    private javax.swing.JComboBox<String> jenisParfum;
    private javax.swing.JTextField namaPelanggan;
    private javax.swing.JTextField noTelepon;
    private javax.swing.JTable tabelDataKasir;
    private javax.swing.JTextField totalPembayaran;
    // End of variables declaration//GEN-END:variables
}
