/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appKasirLaundry;

/**
 *
 * @author HP
 */
import javax.swing.*;
//import javax.swing.event.ChangeEvent;
//import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

public class appKasirISL extends javax.swing.JFrame {

    int idCounter = 1; // Counter untuk ID pelanggan otomatis

    /**
     * Creates new form appKasirISL
     */
    public appKasirISL() {
        initComponents();
        generateIdPelanggan(); // Inisialisasi ID
        setNoTelepon(); // Membatasi input noTelepon hanya untuk angka
        comboBoxData(); // Inisialisasi data ComboBox
        setupBeratSpinner(); // Konfigurasi spinner "Berat"
    }

    private void generateIdPelanggan() {
        id_pelanggan.setText("KL-ISL" + String.format("%04d", idCounter)); // Format ID jadi KLS0001, dst.   
        id_pelanggan.setEditable(false); // ID pelanggan tidak bisa diubah
    }

    private void setNoTelepon() {
        // Pendekatan menggunakan KeyListener
        noTelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char angka = evt.getKeyChar();
                if (!Character.isDigit(angka)) {
                    evt.consume(); // Batalkan input jika bukan angka
                }
            }
        });
    }

    private void comboBoxData() {
        jenisLayanan.addItem("Cuci Kering");
        jenisLayanan.addItem("Cuci Setrika");
        jenisLayanan.addItem("Setrika Saja");
        jenisLayanan.addItem("Dry Cleaning");

        jenisBarang.addItem("Pakaian");
        jenisBarang.addItem("Sprei");
        jenisBarang.addItem("Selimut");
        jenisBarang.addItem("Jas");

        jenisParfum.addItem("-");
        jenisParfum.addItem("Lavender");
        jenisParfum.addItem("Mawar");
        jenisParfum.addItem("Jeruk");
    }

    private void setupBeratSpinner() {
        // Model spinner dengan nilai awal = 1, minimum = 1, maksimum = 50, step = 1
        SpinnerNumberModel beratModel = new SpinnerNumberModel(1, 1, 50, 1);
        Berat.setModel(beratModel);

        // Nonaktifkan kemampuan mengetik manual
        JSpinner.DefaultEditor editor = (JSpinner.DefaultEditor) Berat.getEditor();
        editor.getTextField().setEditable(false); // Membuat text field tidak bisa diedit

        // Listener untuk memastikan nilai tidak kurang dari 1
//        SpinnerNumberModel model = new SpinnerNumberModel(1, 1, Integer.MAX_VALUE, 1);
//Berat = new JSpinner(model);
//        Berat.addChangeListener(new ChangeListener() {
//            @Override
//            public void stateChanged(ChangeEvent e) {
//                int value = (int) Berat.getValue();
//                if (value < 1) {
//                    Berat.setValue(1); // Tetapkan nilai minimum ke 1
//                }
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        Berat = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        noTelepon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jenisLayanan = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jenisBarang = new javax.swing.JComboBox<>();
        totalBayarJ = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaPelanggan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        id_pelanggan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jenisParfum = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataKasir = new javax.swing.JTable();
        hapusData = new javax.swing.JButton();
        totalHargaJ = new javax.swing.JTextField();
        hapusDataAll = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        totalDiskon = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        totalPembayaran1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel14.setText("(kg)");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(610, 313, 42, 16);

        harga.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        getContentPane().add(harga);
        harga.setBounds(355, 422, 110, 20);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(427, 381, 72, 23);

        Berat.setBorder(null);
        Berat.setVerifyInputWhenFocusTarget(false);
        Berat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BeratStateChanged(evt);
            }
        });
        getContentPane().add(Berat);
        Berat.setBounds(355, 310, 249, 20);

        jLabel7.setText("No Telepon                :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 180, 130, 16);

        alamat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        getContentPane().add(alamat);
        alamat.setBounds(355, 214, 249, 20);

        jLabel8.setText("Alamat                        :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 220, 130, 16);

        noTelepon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        noTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTeleponActionPerformed(evt);
            }
        });
        getContentPane().add(noTelepon);
        noTelepon.setBounds(355, 180, 249, 20);

        jLabel9.setText("Jenis Layanan          :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 250, 130, 16);

        jenisLayanan.setBorder(null);
        getContentPane().add(jenisLayanan);
        jenisLayanan.setBounds(355, 242, 249, 20);

        jLabel10.setText("Jenis Barang            :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 280, 130, 16);

        jenisBarang.setBorder(null);
        jenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisBarangActionPerformed(evt);
            }
        });
        getContentPane().add(jenisBarang);
        jenisBarang.setBounds(355, 276, 249, 20);

        totalBayarJ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        totalBayarJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBayarJActionPerformed(evt);
            }
        });
        getContentPane().add(totalBayarJ);
        totalBayarJ.setBounds(640, 460, 120, 20);

        jLabel11.setText("Berat                           :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(220, 310, 130, 16);

        jLabel12.setText("Harga  (kg)                :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(220, 430, 130, 16);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("KASIR LAUNDRY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(441, 12, 110, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ISL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(491, 38, 17, 16);

        jLabel3.setText("Jl. Bendungan Siguragura No. 31D ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(409, 60, 230, 16);

        jLabel4.setText("HP : 0892381782109");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(449, 82, 170, 16);

        jLabel5.setText("ID Pelanggan            :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 110, 130, 16);

        namaPelanggan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        namaPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPelangganActionPerformed(evt);
            }
        });
        getContentPane().add(namaPelanggan);
        namaPelanggan.setBounds(360, 150, 240, 20);

        jLabel6.setText("Nama Pelanggan     :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 150, 120, 16);

        id_pelanggan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        id_pelanggan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        id_pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_pelangganActionPerformed(evt);
            }
        });
        getContentPane().add(id_pelanggan);
        id_pelanggan.setBounds(355, 110, 249, 22);

        jLabel15.setText("Total Pembayaran         :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(490, 460, 180, 16);

        jLabel13.setText("Jenis Parfum            :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(220, 350, 130, 16);

        jenisParfum.setBorder(null);
        getContentPane().add(jenisParfum);
        jenisParfum.setBounds(355, 347, 249, 20);

        tabelDataKasir.setAutoCreateRowSorter(true);
        tabelDataKasir.setBackground(new java.awt.Color(102, 204, 255));
        tabelDataKasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pelanggan", "Nama Pengguna", "No Telepon", "Alamat", "Jenis Layanan", "Jenis Barang", "Berat", "Harga(kg)", "Jenis Parfum", "Diskon", "Total Bayar", "Setelah Diskon "
            }
        ));
        tabelDataKasir.setCellSelectionEnabled(true);
        tabelDataKasir.setSelectionBackground(new java.awt.Color(51, 0, 102));
        tabelDataKasir.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelDataKasir.setShowGrid(true);
        tabelDataKasir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelDataKasirKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataKasir);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 510, 1080, 78);

        hapusData.setText("Hapus Data");
        hapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusDataActionPerformed(evt);
            }
        });
        getContentPane().add(hapusData);
        hapusData.setBounds(30, 590, 130, 23);

        totalHargaJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalHargaJActionPerformed(evt);
            }
        });
        getContentPane().add(totalHargaJ);
        totalHargaJ.setBounds(640, 420, 120, 22);

        hapusDataAll.setText("Bersihkan JFrame");
        hapusDataAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusDataAllActionPerformed(evt);
            }
        });
        getContentPane().add(hapusDataAll);
        hapusDataAll.setBounds(170, 590, 160, 23);

        jLabel16.setText("Total Diskon             :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(220, 460, 130, 16);

        totalDiskon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        totalDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalDiskonActionPerformed(evt);
            }
        });
        getContentPane().add(totalDiskon);
        totalDiskon.setBounds(355, 456, 110, 20);

        jLabel20.setText("Total Harga                    :");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(490, 420, 170, 16);

        BG.setBackground(new java.awt.Color(102, 204, 255));
        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appKasirLaundry/gamabr.png"))); // NOI18N
        getContentPane().add(BG);
        BG.setBounds(-120, -10, 1240, 630);

        jLabel17.setText("Total Pembayaran         :");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(517, 459, 160, 16);

        jLabel18.setText("Total Pembayaran         :");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(517, 459, 160, 16);

        jLabel19.setText("Total Pembayaran         :");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(517, 459, 160, 16);

        totalPembayaran1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        totalPembayaran1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPembayaran1ActionPerformed(evt);
            }
        });
        getContentPane().add(totalPembayaran1);
        totalPembayaran1.setBounds(660, 460, 120, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:

        // Validasi input
        if (namaPelanggan.getText().trim().isEmpty()
                || noTelepon.getText().trim().isEmpty()
                || alamat.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Harap isi semua data terlebih dahulu!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; // Menghentikan eksekusi jika ada input yang kosong
        }
        // Mendapatkan pilihan dari combo box
        String layanan = (String) jenisLayanan.getSelectedItem();
        String barang = (String) jenisBarang.getSelectedItem();
        String parfum = (String) jenisParfum.getSelectedItem();
        int berat = (int) Berat.getValue();

        // Menentukan harga per item
        int hargaLayanan = 0, hargaBarang = 0, hargaParfum = 0;

        // Harga berdasarkan layanan
        switch (layanan) {
            case "Cuci Kering":
                hargaLayanan = 2000;
                break;
            case "Cuci Setrika":
                hargaLayanan = 3000;
                break;
            case "Setrika Saja":
                hargaLayanan = 1000;
                break;
            case "Dry Cleaning":
                hargaLayanan = 5000;
                break;
        }

        // Harga berdasarkan barang
        switch (barang) {
            case "Pakaian":
                hargaBarang = 4000;
                break;
            case "Sprei":
                hargaBarang = 6000;
                break;
            case "Selimut":
                hargaBarang = 8000;
                break;
            case "Jas":
                hargaBarang = 7000;
                break;
        }

        // Harga berdasarkan parfum
        switch (parfum) {
            case "Lavender":
                hargaParfum = 2000;
                break;
            case "Mawar":
                hargaParfum = 1500;
                break;
            case "Jeruk":
                hargaParfum = 1000;
                break;
            default:
                hargaParfum = 0; // Harga 0 jika parfum tidak dipilih
                break;
        }

        // Menghitung total harga per kilogram
        int hargaPerKg = hargaLayanan + hargaBarang;
        int totalHargaKg = (hargaPerKg * berat);
        harga.setText(String.valueOf(totalHargaKg)); // Menampilkan harga per kilogram dxi input Harga(kg)

        // Menghitung total pembayaran sebelum diskon
        int totalHarga = (hargaPerKg * berat) + hargaParfum;
        totalHargaJ.setText(String.valueOf(totalHarga));

        // Menghitung total Diskon (hanya 10% dari totalBayar jika > 100000)
        int diskon = 0;
        if (totalHarga > 100000) {
            diskon = totalHarga * 10 / 100; // Diskon 10%   
        }
        totalDiskon.setText(String.valueOf(diskon)); // Menampilkan total diskon saja

        // Menghitung total pembayaran setelah diskon
        int totalBayar = totalHarga - diskon;
        totalBayarJ.setText(String.valueOf(totalBayar)); // Menampilkan total pembayaran setelah diskon

        // Membuat ID Pelanggan baru berdasarkan counter
        String idPelanggan = "KL-ISL" + String.format("%04d", idCounter++);

        // Menampilkan popup dengan hasil perhitungan
        JOptionPane.showMessageDialog(this,
                "ID Pelanggan  : " + idPelanggan
                + "\nNama Pelanggan  : " + namaPelanggan.getText()
                + "\nNo Telepon  : " + noTelepon.getText()
                + "\nAlamat  : " + alamat.getText()
                + "\nJenis Layanan  : " + layanan
                + "\nJenis Barang  : " + barang
                + "\nBerat  : " + berat + " kg"
                + "\nHarga per Kg  : Rp " + hargaPerKg
                + "\nJenis Parfum  : " + parfum
                + "\nTotal Diskon  : Rp " + diskon
                + "\nTotal Harga  : Rp " + totalHarga
                + "\nTotal Bayar  : Rp " + totalBayar,
                "Hasil Perhitungan", JOptionPane.INFORMATION_MESSAGE);

        // Tambahkan data ke tabel
        DefaultTableModel model = (DefaultTableModel) tabelDataKasir.getModel();
        model.addRow(new Object[]{
            idPelanggan, namaPelanggan.getText(), noTelepon.getText(), alamat.getText(),
            layanan, barang, berat, hargaPerKg, parfum, diskon, totalHarga, totalBayar
        });

        // Update ID pelanggan di label setelah menambah data
        id_pelanggan.setText("KL-ISL" + String.format("%04d", idCounter)); // Update ID di label

        // Reset form input
        namaPelanggan.setText(""); // Reset Nama Pelanggan
        noTelepon.setText(""); // Reset No Telepon
        alamat.setText(""); // Reset Alamat
        jenisLayanan.setSelectedIndex(0); // Reset ComboBox Jenis Layanan
        jenisBarang.setSelectedIndex(0); // Reset ComboBox Jenis Barang
        jenisParfum.setSelectedIndex(0); // Reset ComboBox Jenis Parfum
        Berat.setValue(1); // Reset Spinner Berat
        harga.setText(""); // Reset Harga
        totalHargaJ.setText(""); // Reset Harga
        totalDiskon.setText(""); // Reset Total Diskon
        totalBayarJ.setText(""); // Reset Total Pembayaran
    }//GEN-LAST:event_hitungActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void noTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTeleponActionPerformed

    private void jenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisBarangActionPerformed

    private void totalBayarJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBayarJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBayarJActionPerformed

    private void namaPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPelangganActionPerformed

    private void id_pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_pelangganActionPerformed

    private void hapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusDataActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabelDataKasir.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) tabelDataKasir.getModel();
            model.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!");
        }
    }//GEN-LAST:event_hapusDataActionPerformed

    private void hapusDataAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusDataAllActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelDataKasir.getModel();
        model.setRowCount(0); // Menghapus semua data di tabel
    }//GEN-LAST:event_hapusDataAllActionPerformed

    private void BeratStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BeratStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BeratStateChanged

    private void totalDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalDiskonActionPerformed

    private void totalPembayaran1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPembayaran1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPembayaran1ActionPerformed

    private void totalHargaJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalHargaJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalHargaJActionPerformed

    private void tabelDataKasirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelDataKasirKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelDataKasirKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appKasirISL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appKasirISL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appKasirISL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appKasirISL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appKasirISL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JSpinner Berat;
    private javax.swing.JTextField alamat;
    private javax.swing.JButton hapusData;
    private javax.swing.JButton hapusDataAll;
    private javax.swing.JTextField harga;
    private javax.swing.JButton hitung;
    private javax.swing.JTextField id_pelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenisBarang;
    private javax.swing.JComboBox<String> jenisLayanan;
    private javax.swing.JComboBox<String> jenisParfum;
    private javax.swing.JTextField namaPelanggan;
    private javax.swing.JTextField noTelepon;
    private javax.swing.JTable tabelDataKasir;
    private javax.swing.JTextField totalBayarJ;
    private javax.swing.JTextField totalDiskon;
    private javax.swing.JTextField totalHargaJ;
    private javax.swing.JTextField totalPembayaran1;
    // End of variables declaration//GEN-END:variables
}
